clc;
clear all;
close all;

%Free Space
c = 3 * 10 .^ 8;
w = 1 * 10 .^ 8; 
beta = w/c;
t = -1.5 : 0.01 : 1;
x = -1.5 : 0.01 : 1;
m = zeros(size(t));
Ey = 30 * cos(w * t - beta * x);
Hz = (30/377) * cos(w * t - beta * x); 
plot3(x, Ey, m, 'r');
hold on;
plot3(x, m, Hz, 'g');
grid on;
hold off;
title('EM Wave Components in Free Space');
xlabel('Direction of wave'); 
ylabel('Electric Field'); 
zlabel('Magnetic Field');

%Good Conductors c = 3 * 10 .^ 8;
w = 1 * 10 .^ 8;
mu = 0.99999 * pi * 10 .^ (-7);
epsilon = 1 * 8.854 * 10 .^ (-12);
sigma = 50;
k = (mu * sigma) / 2;
alpha = (sqrt(k * w)); 
beta = (sqrt(k * w));
ita = sqrt((w * mu) / sigma); 
theta = pi / 4;
t = -3 : 0.01 : 0.5;
x = -3 : 0.01 : 0.5;
m = zeros(size(t));
Ey = 30 * cos(w * t - beta * x) .* exp(-alpha * x);
Hz = (30 / ita) * cos(w * t - beta * x - theta) .* exp(-alpha * x); 
figure;
plot3(x, Ey, m, 'r'); hold on;
plot3(x, m, Hz, 'g'); grid on;
hold off;
xlabel('Direction of wave'); 
ylabel('Electric Field'); 
zlabel('Magnetic Field');
title('Em Wave components in Good Conductors'); 
view(10, 10);

%Lossless Dielectric c = 3 * 10 .^ 8;
w = 1 * 10 .^ 8;
alpha = 0;
mu = 1 * 4 * pi * 10 .^ (-7);
epsilon = 3.7 * 8.854 * 10 .^ (-12);
beta = w * sqrt(mu * epsilon);
ita = sqrt(mu / epsilon);
t = -1.5 : 0.01 : 1;
x = -1.5 : 0.01 : 1;
m = zeros(size(t));
Ey = 30 * cos(w * t - beta * x) .* exp(-alpha * x);
Hz = (30 / ita) * cos(w * t - beta * x) .* exp(-alpha * x); 
figure;
plot3(x, Ey, m, 'r');
hold on;
plot3(x, m, Hz, 'g'); 
grid on;
hold off;
xlabel('Direction of wave'); 
ylabel('Electric Field'); 
zlabel('Magnetic Field');
title('Em Wave components in Lossless Dielectric Medium'); 
view(10, 10);


%Lossy Dielectric c = 3 * 10 .^ 8;
w = 1 * 10 .^ 8;
mu = 1 * 4 * pi * 10 .^ (-7);
epsilon = 3.7 * 8.854 * 10 .^ (-12);
sigma = 0.64;
k = (mu * epsilon) / 2;
alpha = w * (sqrt(k * (sqrt(1 + (sigma / (w * epsilon)) .^ 2) - 1))); 
beta = w * (sqrt(k * (sqrt(1 + (sigma / (w * epsilon)) .^ 2) + 1)));
ita = (sqrt(mu / epsilon)) / (1 + (sigma / (w * epsilon)) .^ 2) .^ (0.25);
theta = 0.5 * atan(sigma / (w * epsilon));
t = -3 : 0.01 : 0.5;
x = -3 : 0.01 : 0.5;
m = zeros(size(t));
Ey = 30 * cos(w * t - beta * x) .* exp(-alpha * x);
Hz = (30 / ita) * cos(w * t - beta * x - theta) .* exp(-alpha * x); 
figure;
plot3(x, Ey, m, 'r'); 
hold on;
plot3(x, m, Hz, 'g');
grid on;
hold off;
xlabel('Direction of wave'); 
ylabel('Electric Field'); 
zlabel('Magnetic Field');
title('Em Wave components in Lossy Dielectric Medium'); 
view(10, 10);