n=linspace(-10,10)
x=sinc(n)
xft=fft(x,256);
xabs=fftshift(abs(xft))
subplot(3,1,1)
stem(n,x,"r-","LineWidth",1)
xlabel('n---->')
ylabel('sinc(n)--->')
title('Plot of sinc function')
subplot(3,1,2)
plot(xabs,'b-',"LineWidth",1)
xlabel('frequency')
ylabel('X(f)')
title('Magnitude response of fourier transform of sinc function')
subplot(3,1,3)
plot(angle(xft),'k-','LineWidth',1)
xlabel('n--->')
ylabel('sinc(n)-->')
title('Phase response of fourier transform of sinc function')